USE #DatabaseName#
SELECT  
	  COL.COLUMN_NAME AS COLUMNNAME
	, COLUMNPROPERTY(OBJECT_ID('#TableName#'), COL.COLUMN_NAME, 'IsIdentity') AS IS_IDENTITY
	, CASE WHEN TAB.CONSTRAINT_TYPE = 'PRIMARY KEY'  THEN 1 ELSE 0 END AS IS_PRIMARYKEY
	, CASE WHEN TAB.CONSTRAINT_TYPE = 'FOREIGN KEY'  THEN 1 ELSE 0 END AS IS_FOREIGNKEY
	, OBJECT_NAME(FK.REFERENCED_OBJECT_ID) As TABLE_FOREIGNKEY
	, CASE 
		WHEN COL.DATA_TYPE = 'smallint' THEN 'Int16'
		WHEN COL.DATA_TYPE = 'binary' THEN 'Int16'
		WHEN COL.DATA_TYPE = 'tinyint' THEN 'Int16'
		WHEN COL.DATA_TYPE = 'varbinary' THEN 'Int32'
		WHEN COL.DATA_TYPE = 'int' THEN 'Int32'
		WHEN COL.DATA_TYPE = 'bigint' THEN 'Int64'
		WHEN COL.DATA_TYPE = 'bit' THEN 'Boolean'
		WHEN COL.DATA_TYPE = 'char' THEN 'String'
		WHEN COL.DATA_TYPE = 'nvarchar' THEN 'String'
		WHEN COL.DATA_TYPE = 'nchar' THEN 'String'
		WHEN COL.DATA_TYPE = 'ntext' THEN 'Text'
		WHEN COL.DATA_TYPE = 'sysname' THEN 'String'
		WHEN COL.DATA_TYPE = 'text' THEN 'Text'
		WHEN COL.DATA_TYPE = 'varchar' THEN 'String'
		WHEN COL.DATA_TYPE = 'xml' THEN 'String'
		WHEN COL.DATA_TYPE = 'datetime' THEN 'DateTime'
		WHEN COL.DATA_TYPE = 'timestamp' THEN 'DateTime'
		WHEN COL.DATA_TYPE = 'smalldatetime' THEN 'DateTime'
		WHEN COL.DATA_TYPE = 'decimal' THEN 'Double'
		WHEN COL.DATA_TYPE = 'float' THEN 'Double'
		WHEN COL.DATA_TYPE = 'money' THEN 'Double'
		WHEN COL.DATA_TYPE = 'smallmoney' THEN 'Double'
		WHEN COL.DATA_TYPE = 'numeric' THEN 'Double'
		WHEN COL.DATA_TYPE = 'real' THEN 'Double'
		ELSE 'Int32'
	 END AS DATA_TYPE
	,ISNULL(COL.CHARACTER_MAXIMUM_LENGTH,0) DATA_SIZE
	,IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS COL
LEFT JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE COLU
	  ON COLU.COLUMN_NAME = COL.COLUMN_NAME 
	AND COLU.TABLE_NAME = COL.TABLE_NAME
LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS TAB
	  ON COLU.CONSTRAINT_NAME = TAB.CONSTRAINT_NAME 
	AND COLU.TABLE_NAME = TAB.TABLE_NAME
LEFT JOIN  SYS.FOREIGN_KEYS FK
	  ON  FK.PARENT_OBJECT_ID = OBJECT_ID('#TableName#')
	AND  FK.NAME = TAB.CONSTRAINT_NAME
WHERE COL.TABLE_NAME = '#TableName#'
ORDER BY COL.ORDINAL_POSITION
