DROP TABLE [dbo].[TIMESHEET]
GO
CREATE TABLE [dbo].[TIMESHEET]
(
	 [ID_TIMESHEET] INT IDENTITY(1,1) NOT NULL
	,[DATE_RG] DATE NOT NULL
	,[START_AM] TIME NULL
	,[END_AM] TIME NULL
	,[START_PM] TIME NULL
	,[END_PM] TIME NULL
	,[DESCRIPTION] VARCHAR(500) NULL
)
GO


DROP TABLE [dbo].[TASK]
GO
CREATE TABLE [dbo].[TASK]
(
	 [ID_TASK] INT IDENTITY(1,1) NOT NULL
	,[START_TM] TIME NULL
	,[END_TM] TIME NULL
	,[DESCRIPTION] VARCHAR(500) NULL
	,[INDICE_PROJECT] VARCHAR(10) NOT NULL
	,[ID_TIMESHEET] INT
	,[ID_PROJECT] INT
)
GO

DROP TABLE [dbo].[PROJECT]
GO
CREATE TABLE [dbo].[PROJECT]
(
	 [ID_PROJECT] INT IDENTITY(1,1) NOT NULL
	,[START_DT] DATETIME NOT NULL
	,[END_DT]  DATETIME 
	,[NAME] VARCHAR(1000) NOT NULL
	,[ALIAS] VARCHAR(50) NOT NULL
	,[DESCRIPTION] VARCHAR(500) NULL
)
GO


DROP TABLE [dbo].[PARAMETER]
GO
CREATE TABLE [dbo].[PARAMETER]
(
	 [KEY] CHAR(100)
	,[VALUE] VARCHAR(8000) 
)
GO
